{ config, pkgs, ... }:
{
  wayland.windowManager.hyprland = {
    enable = true;
    autogenerated = 1;
    settings = {
      "$mod" = "SUPER";
      "$terminal" = "kitty";
      "$fileManager" = "thunar";
      "$menu" = "pkill rofi || rofi -show drun";
      "$taskManager" = "kitty -e btop";
      "$browser" = "brave";

      "$shutdown" = "hyprshutdown --post-cmd 'poweroff'"
      "$lock" = "loginctl lock-session"

      "$zoomIn" = "hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.4')"
      "$zoomOut" = "hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.6') | if . < 1 then 1 else . end')"




      # animations{} are all that is left


      ########################## BINDS #####################################
      bind = [ # normal binds
        "$mod, return, exec, $terminal" 
        "$mod, Q, killactive" 
        "$mod, M, exit" 
        "$mod, E, exec, $fileManager" 
        "$mod, B, exec, $browser" 
        "$mod, V, togglefloating" 
        "$mod, W, exec, $menu" 
        "$mod, L, exec, $lock" 
        "ALT, Return, fullscreen" 

        "CTRL ALT, Delete, exec, $shutdown"

	#"$mod, P, pseudo," #dwindle?
	#"$mod, J, togglesplit," #dwindle?
	#"$mod SHIFT, S, movetoworkspace, special:magic" #scratchpad?


        # moving focus
        "$mod, H, movefocus, l" 
        "$mod, L, movefocus, r" 
        "$mod, K, movefocus, u" 
        "$mod, J, movefocus, d" 

        # # numbered workspaces
        # "$mod, 1, workspace, 1" 
        # "$mod, 2, workspace, 2" 
        # "$mod, 3, workspace, 3" 
        # "$mod, 4, workspace, 4" 
        # "$mod, 5, workspace, 5" 
        # "$mod, 6, workspace, 6" 
        # "$mod, 7, workspace, 7" 
        # "$mod, 8, workspace, 8" 
        # "$mod, 9, workspace, 9" 
        # "$mod, 0, workspace, 10" 
        # "$mod SHIFT, 1, movetoworkspace, 1" 
        # "$mod SHIFT, 2, movetoworkspace, 2" 
        # "$mod SHIFT, 3, movetoworkspace, 3" 
        # "$mod SHIFT, 4, movetoworkspace, 4" 
        # "$mod SHIFT, 5, movetoworkspace, 5" 
        # "$mod SHIFT, 6, movetoworkspace, 6" 
        # "$mod SHIFT, 7, movetoworkspace, 7" 
        # "$mod SHIFT, 8, movetoworkspace, 8" 
        # "$mod SHIFT, 9, movetoworkspace, 9" 
        # "$mod SHIFT, 0, movetoworkspace, 10" 

        # left and right
        "$mod, D, workspace, -1" 
        "$mod, F, workspace, +1" 
        "$mod SHIFT, D, movetoworkspace, -1" 
        "$mod SHIFT, F, movetoworkspace, +1" 
        "$mod, mouse_down, workspace, e-1" 
        "$mod, mouse_up, workspace, e+1" 
      ];
      
      #################### ZOOMING #######################3
      bind = [
        "$mod, plus, exec, $zoomIn" 
        "$mod, minus, exec, $zoomOut" 
      ];
      bindm = [ 
        "$mod CTRL, mouse_up, exec, $zoomIn" 
        "$mod CTRL, mouse_down, exec, $zoomOut"
      ];

      ################ MOUSE BINDS ###########################
      bindm = [ 
        "$mod, mouse:272, movewindow" 
        "$mod, mouse:273, resizewindow" 
      ];

      ################ VOLUME, BRIGHTNESS, AND MEDIA ########################
      bindel = [ 
        #https://github.com/ErikReider/SwayOSD
        ",XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise"
        ",XF86AudioLowerVolume, exec, swayosd-client --output-volume lower"
        ",XF86AudioMute, exec, swayosd-client --output-volume mute-toggle"
        ",XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle"

        ",XF86MonBrightnessUp, exec, swayosd-client --brightness raise"
        ",XF86MonBrightnessDown, exec, swayosd-client --brightness lower"
      ];
      bindl = [
        ",XF86AudioPause, exec, swayosd-client --playerctl play-pause"
        ",XF86AudioPlay, exec, swayosd-client --playerctl play-pause"
        ",XF86AudioPrev, exec, swayosd-client --playerctl previous"
        ",XF86AudioNext, exec, swayosd-client --playerctl next"
      ];
      #", Print, exec, grimblast copy area"


      ################ SPECIAL WORKSPACES ############################
      workspace = { "special:hyprmon, on-created-empty:[float; focus; maximize] kitty -e hyprmon, persistent:false" };
      bind = "$mod, P, togglespecialworkspace, hyprmon";

      workspace = { "special:nrs, on-created-empty:[float; focus; maximize] kitty sh -c 'printf \"Rebuilding..\n\"; nrs; read -p \"Press Enter to continue...\"', persistent:false" };
      bind = "$mod SHIFT, R, togglespecialworkspace, nrs";

      workspace = { "special:btop, on-created-empty:[float; focus; maximize] kitty -e btop, persistent:false" };
      bind = "CTRL SHIFT, Escape, togglespecialworkspace, btop";


      ################ WORKSPACES 1-10 #############################
      ++ (
        builtins.concatLists (builtins.genList (
            x: let
              ws = let
                c = (x + 1) / 10;
              in
                builtins.toString (x + 1 - (c*10));
            in [
              "$mod, ${ws}, workspace, ${toString (x + 1)}"
              "$mod SHIFT, ${ws}, movetoworkspace, ${toString (x + 1)}"
            ]
          )
          10)
      );








      general {
        "gaps_in = 5"
        "gaps_out = 10" #default 20
        "border_size = 2"
        "col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg"
        "col.inactive_border = rgba(595959aa)"
        "resize_on_border = true" #default false
        "allow_tearing = false"
        "layout = dwindle"
      };




      windowrule = { # Ignore maximize requests from all apps
	"name = suppress-maximize-events"
	"match:class = .*"
	"suppress_event = maximize"
      };
      windowrule = { # Fix some dragging issues with XWayland
	"name = fix-wayland-drags"
	"match:class = ^$"
	"match:title = ^$"
	"match:xwayland = true"
	"match:float = true"
	"match:fullscreen = false"
	"match:pin = false"
	"no_focus = true"
      };
      windowrule = { # Hyprland-run windowrule
        "name = move-hyprland-run"
	"match:class = hyprland-run"
	"move = 20 monitor_h-120"
	"float = yes"
      };


      misc = {
        "force_default_wallpaper = 1" # Set to 0 or 1 to disable anime mascot wallpapers
	"disable_hyprland_logo = false"
      };


      master = { "new_status = master" };

      dwindle = {
        "pseudotile = true" # Master switch for pseudotiling
	"preserve_split = true"  # You probably want this
      };











      input = {
        "kb_layout = se"
	"kb_variant ="
	"kb_model ="
	"kb_options ="
	"kb_rules ="

	"follow_mouse = 0" #default 1	
	"sensitivity = 0" #-1.0 - 1.0, 0 means no modification
	touchpad = {
	  "natural_scroll = true"
	  "scroll_factor = 0.1"
	};
      };

      device = { #device example ############################################################ computer specific
        "name = tpps/2-synaptics-trackpoint"
	"sensitivity= -0.5"
	"scroll_factor = 0.3"
      };

      gesture = { "3, horizontal, workspace" };



      decoration = {
        "rounding = 10"
	"rounding_power = 2"

        # transparency of focused and unfocused windows
	"active_opacity = 1.0"
	"inactive_opacity = 1.0"

        shadow = {
	  "enabled = true"
	  "range = 4"
	  "render_power = 3"
	  "color = rgba(1a1a1aee)"
	};

	blur = {
	  "enabled = true"
	  "size = 3"
	  "passes = 1"
	  "vibrancy = 0.1696"
	};
      };



      exec-once = [
        "systemctl --user start hyprpolkitagent"
        "systemctl --user start hypridle"
        "swayosd-server &"
      ];
      ############ PERMISSIONS #####################
      #ecosystem = { "enforce_permission = 1" };
      permission = [
        "/usr/(bin|local/bin)/grim, screencopy, allow"
        "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow"
        "/usr/(bin|local/bin)/hyprpm, plugin, allow"
      ];
      xwayland = { force_zero_scaling = true }; #unscale xwayland
      env = [
        "XDG_CURRENT_DESKTOP,Hyprland"
        "ELECTRON_OZONE_PLATFORM_HINT,auto"
        "XCURSOR_SIZE,24"
        "HYPRCURSOR_SIZE,24"

        #nvidia specific
        "LIBVA_DRIVER_NAME,nvidia"
        "__GLX_VENDOR_LIBRARY_NAME,nvidia"
        "NVD_BACKEND,direct" 
      ];
    };
  };
}

#bind	Normal keybinding	Most keyboard shortcuts
#bindm	Mouse binding	Dragging, resizing, moving windows
#bindl	Locked keybinding	Works even when a key is held down
#bindel	Exclusive locked binding	For media keys, volume keys, brightness keys
#bindr	Release binding	Trigger when key is released
#bindle	Locked + repeat	For keys that should repeat while held
#binde	Exclusive	Prevents other binds from interfering



#What do these do?
# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]
